### ISSUE TITLE
urdf->wrlでエラー

### ISSUE THREAD

**Issue by YuOhara** [fkanehiro/simtrans#45]
http://fkanehiro.github.io/simtrans/html-ja/usage.htmlに従って変換しているのですが、
```
leus@leus-HP-Z620-Workstation:~$ rosrun xacro xacro.py `rospack find pr2_description`/robots/pr2.urdf.xacro > /tmp/pr2.urdf

leus@leus-HP-Z620-Workstation:~$ simtrans -i /tmp/pr2.urdf -o /tmp/pr2.wrl
2015-11-11 21:41:52 INFO simtrans (version cc56235-py2.7.egg)
2015-11-11 21:41:52 INFO converting from: /tmp/pr2.urdf
2015-11-11 21:41:52 INFO              to: /tmp/pr2.wrl
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans==cc56235', 'console_scripts', 'simtrans')()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-cc56235-py2.7.egg/simtrans/cli.py", line 174, in main
    m = reader.read(options.fromfile, assethandler=handler, options=options)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-cc56235-py2.7.egg/simtrans/urdf.py", line 67, in read
    m = reader.read(fname, assethandler)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-cc56235-py2.7.egg/simtrans/sdf.py", line 71, in read
    d = subprocess.check_output(['gz', 'sdf', '-p', utils.resolveFile(fname)])
  File "/usr/lib/python2.7/subprocess.py", line 566, in check_output
    process = Popen(stdout=PIPE, *popenargs, **kwargs)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1327, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```
というエラーが出てしまいます。

**Comment by YuOhara** [comment]
gazebo seems to be old?

**Comment by YuOhara** [comment]
gazeboを新しくしたら動きました。
gzコマンドがないとエラーがでていたようです
