### ISSUE TITLE
dotへの変換でエラー

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/simtrans#49]
チュートリアルに記載の手順でpr2.urdfをpr2.dotに変換しようとすると以下のエラーが表示されます。

```
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans==408bb45', 'console_scripts', 'simtrans')()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-408bb45-py2.7.egg/simtrans/cli.py", line 193, in main
    writer.write(m, options.tofile, options=options)
TypeError: write() got an unexpected keyword argument 'options'
```

**Comment by fkanehiro** [comment]
graphvizのwriterにoptionsキーワードを追加しました。
