### ISSUE TITLE
sdfからvrmlへの変換でエラー

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/simtrans#50]
チュートリアルの記載で生成された/tmp/pa10/model.sdfをvrmlに変換しようとすると、以下のエラーが発生します。

```
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans==408bb45', 'console_scripts', 'simtrans')()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-408bb45-py2.7.egg/simtrans/cli.py", line 193, in main
    writer.write(m, options.tofile, options=options)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-408bb45-py2.7.egg/simtrans/vrml.py", line 427, in write
    c.name = l.name + "-collision-" + str(uuid.uuid1()).replace('-', '')
NameError: global name 'uuid' is not defined
```

**Comment by fkanehiro** [comment]
uuidをimportしたら少し処理が進んだのですが、今度は以下のようなエラーが発生します。
```
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans==9d161b7-dirty', 'console_scripts', 'simtrans')()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-9d161b7_dirty-py2.7.egg/simtrans/cli.py", line 193, in main
    writer.write(m, options.tofile, options=options)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-9d161b7_dirty-py2.7.egg/simtrans/vrml.py", line 456, in write
    v.data.pretranslate()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-9d161b7_dirty-py2.7.egg/simtrans/model.py", line 296, in pretranslate
    trans2 = numpy.dot(trans, self.getmatrix())
TypeError: unsupported operand type(s) for *: 'float' and 'NoneType'
```

**Comment by fkanehiro** [comment]
self.getmatrix()の対角項にNaNが入っているようです。

**Comment by fkanehiro** [comment]
NaNじゃなくてNone

**Comment by fkanehiro** [comment]
collada.pyでunitmeterがNoneとなっていることが原因。
理由は分からないままに0.01にすると良さそうなのでとりあえずNoneの場合は0.01に設定。

**Comment by fkanehiro** [comment]
と思ったら早速0.01ではダメな場合も発見。pa10では小さくなってしまう。

**Comment by fkanehiro** [comment]
wrl->urdfした時に生成されたdaeでunitmeterが指定されていないことが問題。

**Comment by fkanehiro** [comment]
0.01に設定しないと形状が大きくなってしまうJVRC-1も、Rvizでの表示は問題ない。どこかに情報は入っている？
