### ISSUE TITLE
wrl->urdf->wrlで変換エラー

### ISSUE THREAD

**Issue by fkanehiro** [fkanehiro/simtrans#52]
openhrp3のpa10.main.wrlをurdfに変換し、変換したurdfをwrlに変換しようとすると以下のエラーになる。

```
2015-12-14 09:27:43 tetsujin3 root[6923] INFO simtrans (version 9d161b7_dirty-py2.7.egg)
2015-12-14 09:27:43 tetsujin3 root[6923] INFO converting from: /tmp/pa10.urdf
2015-12-14 09:27:43 tetsujin3 root[6923] INFO              to: /tmp/pa10.wrl
Error [parser_urdf.cc:2768] Unable to call parseURDF on robot model
Error [parser.cc:278] parse as old deprecated model file failed.
Error: SDF parsing the xml failed
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans==9d161b7-dirty', 'console_scripts', 'simtrans')()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-9d161b7_dirty-py2.7.egg/simtrans/cli.py", line 174, in main
    m = reader.read(options.fromfile, assethandler=handler, options=options)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-9d161b7_dirty-py2.7.egg/simtrans/urdf.py", line 67, in read
    m = reader.read(fname, assethandler)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-9d161b7_dirty-py2.7.egg/simtrans/sdf.py", line 79, in read
    d = lxml.etree.parse(open(sdffile))
  File "lxml.etree.pyx", line 3239, in lxml.etree.parse (src/lxml/lxml.etree.c:69955)
  File "parser.pxi", line 1769, in lxml.etree._parseDocument (src/lxml/lxml.etree.c:102257)
  File "parser.pxi", line 1789, in lxml.etree._parseFilelikeDocument (src/lxml/lxml.etree.c:102516)
  File "parser.pxi", line 1684, in lxml.etree._parseDocFromFilelike (src/lxml/lxml.etree.c:101442)
  File "parser.pxi", line 1134, in lxml.etree._BaseParser._parseDocFromFilelike (src/lxml/lxml.etree.c:97069)
  File "parser.pxi", line 582, in lxml.etree._ParserContext._handleParseResultDoc (src/lxml/lxml.etree.c:91275)
  File "parser.pxi", line 683, in lxml.etree._handleParseResult (src/lxml/lxml.etree.c:92461)
  File "parser.pxi", line 622, in lxml.etree._raiseParseError (src/lxml/lxml.etree.c:91757)
lxml.etree.XMLSyntaxError: Document is empty, line 1, column 1
```

**Comment by fkanehiro** [comment]
gzが変換出来ない模様。

**Comment by fkanehiro** [comment]
```
velocity = ""
```

が許されないようですね。

**Comment by fkanehiro** [comment]
lowerやupperも空はだめなようなので、inf, -infをデフォルト値としました。
http://wiki.ros.org/urdf/XML/joint

**Comment by yosuke** [comment]
なるほど、理解しました。

同じモデルを行ったり来たりする変換もテストに加えておくのは有益そうですね。

**Comment by fkanehiro** [comment]
はい、行ったり来たりしても変換できること、変換結果が同一のものとなることが必要と思います。重心など視覚的に確認しづらいですが、この方法である程度は確認できるかなと。
