### ISSUE TITLE
wrl to dae convertor problem

### ISSUE THREAD

**Issue by ghost** [fkanehiro/simtrans#83]
Hello

I am converting a wrl file of a robot to dae file. But I get following results:
Humanoid node
Joint node base_link
  Segment node base_link
  Joint node LJ1
    Segment node Agile_Eye1L
    Joint node LJ4
      Segment node L_agile
  Joint node LJ2
    Segment node Agile_Eye2L
    Joint node LJ3
      Segment node Agile_Eye3L
      Joint node LJ5
        Segment node Agile_Eye4L
        Joint node LJ6
          Segment node L_Slider
          Joint node LJ7
            Segment node L_Slider_Moving
            Joint node LJ8
              Segment node L_Rot
              Joint node LJ9
                Segment node L_Rot_Slider
                Joint node LJ10
                  Segment node L_Rot_Slider_Moving
                  Joint node LJ11
                    Segment node L_Back
                    Joint node LJ14
                      Segment node L_base
                Joint node LJ12
                  Segment node L_Knee
                  Joint node LJ13
                    Segment node L_Foot
  Joint node RJ1
    Segment node Agile_Eye1
    Joint node RJ4
      Segment node R_agile
  Joint node RJ2
    Segment node Agile_Eye2
    Joint node RJ3
      Segment node Agile_Eye3
      Joint node RJ5
        Segment node Agile_Eye4
        Joint node RJ6
          Segment node R_Slider
          Joint node RJ7
            Segment node R_Slider_Moving
            Joint node RJ8
              Segment node R_Rot
              Joint node RJ9
                Segment node R_Rot_Slider
                Joint node RJ10
                  Segment node R_Rot_Slider_Moving
                  Joint node RJ11
                    Segment node R_Back
                    Joint node RJ14
                      Segment node R_base
                Joint node RJ12
                  Segment node R_Knee
                  Joint node RJ13
                    Segment node R_Foot
The model was successfully loaded ! 
omniORB: To endpoint: giop:tcp:[::ffff:142.58.187.59]:36298. System exception MARSHAL(YES,MARSHAL_MessageSizeExceedLimitOnClient) while (un)marshalling. Send GIOP 1.2 MessageError.
omniORB: From endpoint: giop:tcp:142.58.187.59:35177. Detected GIOP 1.2 protocol error in input message. giopImpl12.cc:300. Connection is closed.
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans===1f536da-dirty', 'console_scripts', 'simtrans')()
  File "/usr/local/lib/python2.7/dist-packages/simtrans-1f536da_dirty-py2.7-linux-x86_64.egg/simtrans/cli.py", line 223, in main
    m = read(options.fromfile, handler, options)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-1f536da_dirty-py2.7-linux-x86_64.egg/simtrans/cli.py", line 118, in read
    m = reader.read(fromfile, assethandler=handler, options=options)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-1f536da_dirty-py2.7-linux-x86_64.egg/simtrans/vrml.py", line 131, in read
    self._hrpshapes = self._model._get_shapes()
  File "/usr/local/lib/python2.7/dist-packages/ModelLoader_idl.py", line 469, in _get_shapes
    return _omnipy.invoke(self, "_get_shapes", _0_OpenHRP.ShapeSetInfo._d__get_shapes, args)
omniORB.CORBA.COMM_FAILURE: CORBA.COMM_FAILURE(omniORB.COMM_FAILURE_UnMarshalResults, CORBA.COMPLETED_YES)

Do you know what is the problem here?!
Thank You

**Comment by fkanehiro** [comment]
Hi,

Please increase the value of giopMaxMsgSize in /etc/omniORB.cfg.

**Comment by webbrain-one** [comment]
Hi! I’ve opened [pull request #87](https://github.com/fkanehiro/simtrans/pull/87) to fix this VRML-to-DAE conversion issue. It addresses the failure that happens during shape retrieval for larger models, which caused the CORBA/marshal error and prevented the conversion from completing.
