### ISSUE TITLE
urdf to wrl convertor has an error

### ISSUE THREAD

**Issue by mohamadmahdavian** [fkanehiro/simtrans#84]
Hi

I am trying to convert a urdf file to wrl and I am using following command:
simtrans -i file.urdf -o file.wrl

But I am getting following error. Do you know the reason for this error?

```
Traceback (most recent call last):
  File "/usr/local/bin/simtrans", line 9, in <module>
    load_entry_point('simtrans===1f536da', 'console_scripts', 'simtrans')()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 542, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2569, in load_entry_point
    return ep.load()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2229, in load
    return self.resolve()
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 2235, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/local/lib/python2.7/dist-packages/simtrans-1f536da-py2.7-linux-x86_64.egg/simtrans/cli.py", line 27, in <module>
    from . import urdf
  File "/usr/local/lib/python2.7/dist-packages/simtrans-1f536da-py2.7-linux-x86_64.egg/simtrans/urdf.py", line 51, in <module>
    from . import collada
  File "/usr/local/lib/python2.7/dist-packages/simtrans-1f536da-py2.7-linux-x86_64.egg/simtrans/collada.py", line 33, in <module>
    import collada
  File "/usr/local/lib/python2.7/dist-packages/collada/__init__.py", line 48, in <module>
    from collada import schema
  File "/usr/local/lib/python2.7/dist-packages/collada/schema.py", line 27, in <module>
    'resources/schema-1.4.1.xml').decode('utf-8'))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1184, in resource_string
    self, resource_name
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1457, in get_resource_string
    return self._get(self._fn(self.module_path, resource_name))
  File "/usr/lib/python2.7/dist-packages/pkg_resources/__init__.py", line 1580, in _get
    with open(path, 'rb') as stream:
IOError: [Errno 2] No such file or directory: '/usr/local/lib/python2.7/dist-packages/collada/resources/schema-1.4.1.xml'
```

Thank You

**Comment by fkanehiro** [comment]
Unfortunately, this software has not been maintained for a long time. 
This was developed with ubuntu14.04LTS. 
This will not work due to different version of OS or necessary packages.
